### ISSUE TITLE
Installation problem: requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by dialogik** [kamilabs/BookingBundle#2]
When trying to install this package on Symfony 2.8.25, I get the error message:

> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>    - Installation request for kami/booking-bundle ^1.0 -> satisfiable by kami/booking-bundle[1.0].
>    - Conclusion: remove symfony/debug v2.8.25
>    - Conclusion: don't install symfony/debug v2.8.25
>    - Can only install one of: symfony/symfony[v3.0.9, v2.8.25].
>    - don't install symfony/symfony v2.8.25|remove symfony/twig-bridge v3.0.9
>    - don't install symfony/twig-bridge v3.0.9|don't install symfony/symfony v2.8.25
>    - Installation request for symfony/debug (installed at v2.8.25) -> satisfiable by symfony/debug[v2.8.25], symfony/symfony[v2.8.25].
>    - Installation request for symfony/twig-bridge (installed at v3.0.9) -> satisfiable by symfony/symfony[v3.0.9], symfony/twig-bridge[v3.0.9].

What is the proper Symfony2 version (as there is no Symfony3 support yet)?

**Comment by AndrewUA21** [comment]
https://travis-ci.org/kamilabs/BookingBundle

We do support.

**Comment by tdumalin** [comment]
Hi,
I've noticed two bugs:

- When we are the 30th of the month and using kami_booking_calendar twig function, month render is false, for exemple I changed the date of my system to 2018-09-30 and march 2019 appears twice, I have :
january ,march,march, Apri etc..

- Apparently the definition of your twig extension service 'booking_calendar' is false, first given argument is  '%kami.booking_calendar.class%' but i think it must be '%kami.booker.entity_class%' because you call doctrine repository using this argument.
